name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Cargo fmt
        run: cargo fmt -- --check

      - name: Clippy
        run: cargo clippy

      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: Build wasm for Nodejs
        run: wasm-pack build --scope wasm-dev --release --out-name image --target nodejs

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      # - name: Build wasm for Web
      #   run: wasm-pack build --scope wasm-dev --release --out-name image
      # - name: Install nodejs-app dependencies & Test
      #   run: yarn && yarn test
      #   working-directory: apps/nodejs-app

      - name: Install web-app dependencies & Build
        run: yarn && yarn build
        working-directory: apps/web-app

      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: apps/web-app/dist
